name: CI Pipeline

on: [push]

jobs:
  validate-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: List files (debug)
        run: ls -la

      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q "https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb"
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Run PowerShell Script
        shell: pwsh
        run: |
          pwsh -File ./Create-AzureVM.ps1
